# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d27b2e22fe534fbe8afdc8c4de09528ca81a7d0115fb929a90977f88e32b9fc4c0028dd2ed3de455b4c8c7d8b4dfad228a46cbcfd940586dd652fd201f48e1e5

test:
  secret_key_base: 40533f42ebc98c01f06fe54e3ba8559d1e9c75d6da47903fdd8da518de76ec9e70ac41c31910eb59f1cde55d122e619d9014bff8308801d57422dc1027eed262

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
